const projects={
  'clean-app':{type:'01 / UI/UX DESIGN · MOBILE DEVELOPMENT',title:'MU Clean & Clear App',image:'assets/project1/ChatGPT Image 7 ก.ย. 2569 15_03_21.png',imageLabel:'MU Green & Clean',summary:'A campus reporting app taken from UI/UX concept through to a functional mobile product experience.',tools:['Figma','Wireframing','Prototyping','Dart','Java','MySQL','Mobile Development']},
  commerce:{type:'03 / WEB DEVELOPMENT',title:'E-Commerce Website',image:'assets/project3/image (4).png',images:['assets/project3/image (4).png','assets/project3/image.png','assets/project3/image (1).png','assets/project3/image (2).png','assets/project3/image (3).png'],imageLabel:'Ophtus E-Commerce',summary:'A responsive e-commerce website created for a Web Technologies & Application project.',tools:['Figma','HTML','CSS','JavaScript','MySQL']},
  apartment:{type:'04 / DEVOPS ENGINEERING PROJECT',title:'Apartment Management System',image:'assets/project4/apartment-system-portfolio-showcase.png',imageLabel:'Apartment System · DevOps Engineering Project',summary:'Developed a full-stack apartment management system demonstrating Docker containerization, Kubernetes orchestration, automated testing, and CI/CD. Implemented containerized services with Docker Compose, deployed the application on Minikube, and developed JUnit 5 and Mockito regression tests for core business logic using H2 in a fully local development environment.',role:'Full-stack Developer & DevOps Engineer',focus:'Containerizing services, orchestrating deployments with Kubernetes, and validating core business logic through automated regression testing.',tools:['Java','Spring Boot','Docker Compose','Kubernetes','Minikube','JUnit 5','Mockito','H2','CI/CD']},
  arex:{type:'05 / INTERNSHIP',title:'AREX Platform',image:'assets/project_intern/ChatGPT Image 7 ก.ย. 2569 16_14_31.png',imageLabel:'AREX Platform',summary:'Built chatbots for businesses on websites and LINE Business, and contributed search and filtering features to a real-estate platform connecting buyers and sellers.',tools:['Chatbot','LINE Business','Search','Filtering','Frontend','UI/UX','GitHub']}
};
const dialog=document.querySelector('#project-dialog');
document.querySelectorAll('.project-info button').forEach(button=>{button.textContent=button.textContent.replace(/[↗⟶→]/g,'').trim()});
document.querySelectorAll('.project-card').forEach(card=>card.querySelector('button').addEventListener('click',()=>{const p=projects[card.dataset.project];document.querySelector('#modal-type').textContent=p.type;document.querySelector('#modal-title').textContent=p.title;document.querySelector('#modal-summary').textContent=p.summary;const images=p.images||(p.image?[p.image]:[]);let media=document.querySelector('#modal-media');if(!media){media=document.createElement('div');media.id='modal-media';media.className='modal-media';document.querySelector('#modal-summary').after(media)}media.classList.toggle('single-image',images.length===1);media.innerHTML=images.length?images.map((image,index)=>`<a class="modal-image-link" href="${image}" target="_blank" rel="noreferrer"><img src="${image}" alt="${p.title} screenshot ${index+1}" onerror="this.parentElement.remove()"></a>`).join(''):`<span class="modal-empty">${p.imageLabel}</span>`;document.querySelector('#modal-details').innerHTML='<section><h3>Role & contribution</h3><p>Designed and developed key parts of this project, from idea through implementation.</p></section><section><h3>Project focus</h3><p>Creating a clear, practical experience around real user needs.</p></section>';document.querySelector('#modal-tools').innerHTML=p.tools.map(x=>`<span>${x}</span>`).join('');dialog.showModal()}));
document.querySelectorAll('.project-card').forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.querySelector('button').tabIndex=-1;card.addEventListener('click',event=>{if(!event.target.closest('button'))card.querySelector('button').click()});card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();card.querySelector('button').click()}})});
document.querySelectorAll('.project-card').forEach(card=>card.querySelector('button').addEventListener('click',()=>{const p=projects[card.dataset.project];if(p.role&&p.focus)document.querySelector('#modal-details').innerHTML=`<section><h3>Role & contribution</h3><p>${p.role}</p></section><section><h3>Project focus</h3><p>${p.focus}</p></section>`}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
